### ISSUE TITLE
Ethereum Based Pledges for Skirms

### ISSUE THREAD

**Issue by KyleKaniecki** [KyleKaniecki/Skirmish-Issues#44]
**Feature Subsystem**: Skirms, Tournaments

**Expected Behavior:** 
As a user, I want the ability to enter pay to enter skirms and tournaments using ethereum and all valid ERC20 tokens as payment.

**Actual Behavior:** 
Currently, there is no way for a user to enter a pay to enter skirm or tournament.

**Implementation Steps**: 
### Players
- [x] Users can add their public ethereum address to their accounts

### Skirms
- [ ] Users can create pay to enter 1v1 skirms with smart contracts
- [ ] Users can create pay to enter team skirms with smart contracts
- [ ] Ability for users to report scores independently of skirmish in the smart contract if they so choose
- [ ] Ability for users to withdraw money from the smart contract by sending a message to the default function.
- [ ] Ability for Skirmish to act as a tie breaker for conflicting smart contracts

**Screenshots:** 
N/A

**Additional Information:** 

Each step in this process means that the feature is implemented on both the frontend and backend.
